import inertia from '@inertiajs/vite';
import { wayfinder } from '@laravel/vite-plugin-wayfinder';
import babel from '@rolldown/plugin-babel';
import tailwindcss from '@tailwindcss/vite';
import react, { reactCompilerPreset } from '@vitejs/plugin-react';
import laravel from 'laravel-vite-plugin';
import { bunny } from 'laravel-vite-plugin/fonts';
import { defineConfig } from 'vitest/config';

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.tsx'],
            refresh: true,
            fonts: [
                bunny('Instrument Sans', {
                    weights: [400, 500, 600],
                }),
            ],
        }),
        inertia(),
        react(),
        babel({ presets: [reactCompilerPreset()] }),
        tailwindcss(),
        wayfinder({
            formVariants: true,
        }),
    ],
    test: {
        environment: 'jsdom',
        globals: true,
        setupFiles: ['./tests/frontend/setup.ts'],
        include: [
            'resources/js/**/*.test.{ts,tsx}',
            'tests/frontend/**/*.test.{ts,tsx}',
        ],
        exclude: ['tests/E2E/**', 'node_modules/**', 'vendor/**'],
        coverage: {
            provider: 'v8',
            reporter: ['text', 'html', 'json-summary'],
            reportsDirectory: './coverage',
            include: ['resources/js/**/*.{ts,tsx}'],

            // Coverage measures the code this application authored. The
            // starter kit and generated output are excluded, matching the
            // project's testing policy of not re-testing scaffolding.
            exclude: [
                'resources/js/app.tsx',
                'resources/js/types/**',

                // shadcn primitives.
                'resources/js/components/ui/**',

                // Wayfinder codegen, regenerated by `artisan wayfinder:generate`.
                'resources/js/routes/**',
                'resources/js/actions/**',
                'resources/js/wayfinder/**',

                // Laravel starter kit scaffolding: application shell, two
                // factor authentication, passkeys, and appearance switching.
                // These ship with the kit and are exercised by its own Pest
                // tests, not rewritten for this application.
                'resources/js/layouts/auth/**',
                'resources/js/layouts/app-layout.tsx',
                'resources/js/pages/auth/**',
                'resources/js/pages/settings/**',
                'resources/js/components/app-logo.tsx',
                'resources/js/components/app-logo-icon.tsx',
                'resources/js/components/nav-*.tsx',
                'resources/js/components/user-*.tsx',
                'resources/js/components/passkey-*.tsx',
                'resources/js/components/manage-*.tsx',
                'resources/js/components/two-factor-*.tsx',
                'resources/js/components/appearance-tabs.tsx',
                'resources/js/components/breadcrumbs.tsx',
                'resources/js/components/delete-user.tsx',
                'resources/js/components/heading.tsx',
                'resources/js/components/alert-error.tsx',
                'resources/js/components/input-error.tsx',
                'resources/js/components/password-input.tsx',
                'resources/js/components/text-link.tsx',
                'resources/js/hooks/use-appearance.tsx',
                'resources/js/hooks/use-clipboard.ts',
                'resources/js/hooks/use-current-url.ts',
                'resources/js/hooks/use-flash-toast.ts',
                'resources/js/hooks/use-initials.tsx',
                'resources/js/hooks/use-mobile.tsx',
                'resources/js/hooks/use-mobile-navigation.ts',
                'resources/js/hooks/use-two-factor-auth.ts',
                'resources/js/lib/utils.ts',
            ],

            thresholds: {
                statements: 70,
                branches: 60,
                functions: 70,
                lines: 70,
            },
        },
    },
});
